version: '3'

services:
  keycloak-dev:
    image: kilmajster/keycloak-with-authenticator:test
    build:
      context: .
      dockerfile: src/main/docker/dev.Dockerfile
    ports:
      - '8080:8080'
      - '8787:8787'
    environment:
      DEBUG: 'true'
      DEBUG_PORT: '*:8787'
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
